port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: "My-Proxy-1"
    type: http
    server: 207.228.42.131
    port: 46688
    username: 00QDXWq85Zg8KNo
    password: 9qTGqHqv5TDFFTX

proxy-groups:
  - name: "🚀 手動選擇"
    type: select
    proxies:
      - My-Proxy-1

  - name: "🔁 自動切換"
    type: url-test
    proxies:
      - My-Proxy-1
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: "🌍 全球連線"
    type: select
    proxies:
      - "🚀 手動選擇"
      - "🔁 自動切換"

rules:
  - DOMAIN-SUFFIX,google.com,🌍 全球連線
  - DOMAIN-KEYWORD,facebook,🌍 全球連線
  - DOMAIN-SUFFIX,tw,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🌍 全球連線
